#!/bin/bash
#ip adreslerini ben önemli olanları baz alarak belirledim ama isteğe göre değiştirilebilir.
TARGET=$1
PORTS=(22 80 443 8080)

if [ -z "$TARGET" ]; then
    echo "Hedef IP adresi belirtmelisiniz."
    echo "Kullanım: $0 [IP adresi]"
    exit 1
fi

echo "Hedef: $TARGET"
for PORT in "${PORTS[@]}"; do
    timeout 1 bash -c "echo >/dev/tcp/$TARGET/$PORT" &>/dev/null && echo "Port $PORT açık" || echo "Port $PORT kapalı"
done
